apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-meenalgarg-master
  namespace: kubernetes-cluster-meenalgarg
  labels: 
    app: app-meenalgarg-master
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-meenalgarg-master
  template:
    metadata:
      labels:
        app: app-meenalgarg-master
    spec:
      containers:
        - name: app-meenalgarg-master
          image: meenalgarg2610/i-meenalgarg2610-master:latest
          ports:
            - name: http
              containerPort: 8100
              protocol: TCP
          # envFrom:
          #   - configMapRef: 
          #       name: example-config
          #   - secretRef:
          #       name: secret-info
          resources:
            requests:
              memory: "250Mi"
              cpu: "250m"
            limits:
              memory: "500Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: app-meenalgarg-master
  namespace: kubernetes-cluster-meenalgarg
spec:
  type: NodePort
  selector:
    app: app-meenalgarg-master
  ports:
    - protocol: TCP
      nodePort: 30157
      port: 8100
      targetPort: 8100 
