apiVersion: v1
kind: Namespace
metadata:
  name: kubernetes-cluster-meenalgarg
  labels:
    name: kubernetes-cluster-meenalgarg
---

apiVersion: apps/v1
kind: Deployment
metadata: 
  name: app-meenalgarg-{{BRANCHNAME}}
  namespace: kubernetes-cluster-meenalgarg
  labels: 
    app: app-meenalgarg-{{BRANCHNAME}}
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-meenalgarg-{{BRANCHNAME}}
  template:
    metadata:
      labels:
        app: app-meenalgarg-{{BRANCHNAME}}
    spec:
      containers:
        - name: app-meenalgarg-{{BRANCHNAME}}
          image: meenalgarg2610/i-meenalgarg2610-{{BRANCHNAME}}:{{BUILDNUMBER}}
          ports:
            - name: http
              containerPort: 8100
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: app-meenalgarg-{{BRANCHNAME}}
  namespace: kubernetes-cluster-meenalgarg
spec:
  type: NodePort
  selector:
    app: app-meenalgarg-{{BRANCHNAME}}
  ports:
    - protocol: TCP
      nodePort: {{NODEPORT}}
      port: 8100
      targetPort: 8100 
